##
##  Makefile -- Build procedure for sample yudoufu Apache module
##  Autogenerated via ``apxs -n yudoufu -g''.
##

builddir=.
top_srcdir=/home/moriyoshi/opt/httpd-2.4.12
top_builddir=/home/moriyoshi/opt/httpd-2.4.12
include /home/moriyoshi/opt/httpd-2.4.12/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_yudoufu.o mod_yudoufu.lo mod_yudoufu.slo mod_yudoufu.la yudoufu_handler.o yudoufu_handler.lo yudoufu_handler.slo httpd.o httpd.lo httpd.slo *.ali b~*.adb b~*.ads

#   simple test
test: reload
	lynx -mime_header http://localhost/yudoufu

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

